<?php
/**
 * NetworkCellTowers
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * traccar
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * NetworkCellTowers Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NetworkCellTowers implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Network_cellTowers';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'cell_id' => 'int',
        'location_area_code' => 'int',
        'mobile_country_code' => 'int',
        'mobile_network_code' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'cell_id' => null,
        'location_area_code' => null,
        'mobile_country_code' => null,
        'mobile_network_code' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cell_id' => 'cellId',
        'location_area_code' => 'locationAreaCode',
        'mobile_country_code' => 'mobileCountryCode',
        'mobile_network_code' => 'mobileNetworkCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cell_id' => 'setCellId',
        'location_area_code' => 'setLocationAreaCode',
        'mobile_country_code' => 'setMobileCountryCode',
        'mobile_network_code' => 'setMobileNetworkCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cell_id' => 'getCellId',
        'location_area_code' => 'getLocationAreaCode',
        'mobile_country_code' => 'getMobileCountryCode',
        'mobile_network_code' => 'getMobileNetworkCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cell_id'] = isset($data['cell_id']) ? $data['cell_id'] : null;
        $this->container['location_area_code'] = isset($data['location_area_code']) ? $data['location_area_code'] : null;
        $this->container['mobile_country_code'] = isset($data['mobile_country_code']) ? $data['mobile_country_code'] : null;
        $this->container['mobile_network_code'] = isset($data['mobile_network_code']) ? $data['mobile_network_code'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cell_id
     *
     * @return int
     */
    public function getCellId()
    {
        return $this->container['cell_id'];
    }

    /**
     * Sets cell_id
     *
     * @param int $cell_id cell_id
     *
     * @return $this
     */
    public function setCellId($cell_id)
    {
        $this->container['cell_id'] = $cell_id;

        return $this;
    }

    /**
     * Gets location_area_code
     *
     * @return int
     */
    public function getLocationAreaCode()
    {
        return $this->container['location_area_code'];
    }

    /**
     * Sets location_area_code
     *
     * @param int $location_area_code location_area_code
     *
     * @return $this
     */
    public function setLocationAreaCode($location_area_code)
    {
        $this->container['location_area_code'] = $location_area_code;

        return $this;
    }

    /**
     * Gets mobile_country_code
     *
     * @return int
     */
    public function getMobileCountryCode()
    {
        return $this->container['mobile_country_code'];
    }

    /**
     * Sets mobile_country_code
     *
     * @param int $mobile_country_code mobile_country_code
     *
     * @return $this
     */
    public function setMobileCountryCode($mobile_country_code)
    {
        $this->container['mobile_country_code'] = $mobile_country_code;

        return $this;
    }

    /**
     * Gets mobile_network_code
     *
     * @return int
     */
    public function getMobileNetworkCode()
    {
        return $this->container['mobile_network_code'];
    }

    /**
     * Sets mobile_network_code
     *
     * @param int $mobile_network_code mobile_network_code
     *
     * @return $this
     */
    public function setMobileNetworkCode($mobile_network_code)
    {
        $this->container['mobile_network_code'] = $mobile_network_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


