<?php
/**
 * UserAttributes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * traccar
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * UserAttributes Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserAttributes implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'User_attributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'has_email' => 'bool',
        'has_phone' => 'bool',
        'has_phone_verified' => 'bool',
        'has_deposit' => 'bool',
        'has_ride' => 'bool',
        'sms_code' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'has_email' => null,
        'has_phone' => null,
        'has_phone_verified' => null,
        'has_deposit' => null,
        'has_ride' => null,
        'sms_code' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'has_email' => 'hasEmail',
        'has_phone' => 'hasPhone',
        'has_phone_verified' => 'hasPhoneVerified',
        'has_deposit' => 'hasDeposit',
        'has_ride' => 'hasRide',
        'sms_code' => 'smsCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'has_email' => 'setHasEmail',
        'has_phone' => 'setHasPhone',
        'has_phone_verified' => 'setHasPhoneVerified',
        'has_deposit' => 'setHasDeposit',
        'has_ride' => 'setHasRide',
        'sms_code' => 'setSmsCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'has_email' => 'getHasEmail',
        'has_phone' => 'getHasPhone',
        'has_phone_verified' => 'getHasPhoneVerified',
        'has_deposit' => 'getHasDeposit',
        'has_ride' => 'getHasRide',
        'sms_code' => 'getSmsCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['has_email'] = isset($data['has_email']) ? $data['has_email'] : null;
        $this->container['has_phone'] = isset($data['has_phone']) ? $data['has_phone'] : null;
        $this->container['has_phone_verified'] = isset($data['has_phone_verified']) ? $data['has_phone_verified'] : null;
        $this->container['has_deposit'] = isset($data['has_deposit']) ? $data['has_deposit'] : null;
        $this->container['has_ride'] = isset($data['has_ride']) ? $data['has_ride'] : null;
        $this->container['sms_code'] = isset($data['sms_code']) ? $data['sms_code'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets has_email
     *
     * @return bool
     */
    public function getHasEmail()
    {
        return $this->container['has_email'];
    }

    /**
     * Sets has_email
     *
     * @param bool $has_email has_email
     *
     * @return $this
     */
    public function setHasEmail($has_email)
    {
        $this->container['has_email'] = $has_email;

        return $this;
    }

    /**
     * Gets has_phone
     *
     * @return bool
     */
    public function getHasPhone()
    {
        return $this->container['has_phone'];
    }

    /**
     * Sets has_phone
     *
     * @param bool $has_phone has_phone
     *
     * @return $this
     */
    public function setHasPhone($has_phone)
    {
        $this->container['has_phone'] = $has_phone;

        return $this;
    }

    /**
     * Gets has_phone_verified
     *
     * @return bool
     */
    public function getHasPhoneVerified()
    {
        return $this->container['has_phone_verified'];
    }

    /**
     * Sets has_phone_verified
     *
     * @param bool $has_phone_verified has_phone_verified
     *
     * @return $this
     */
    public function setHasPhoneVerified($has_phone_verified)
    {
        $this->container['has_phone_verified'] = $has_phone_verified;

        return $this;
    }

    /**
     * Gets has_deposit
     *
     * @return bool
     */
    public function getHasDeposit()
    {
        return $this->container['has_deposit'];
    }

    /**
     * Sets has_deposit
     *
     * @param bool $has_deposit has_deposit
     *
     * @return $this
     */
    public function setHasDeposit($has_deposit)
    {
        $this->container['has_deposit'] = $has_deposit;

        return $this;
    }

    /**
     * Gets has_ride
     *
     * @return bool
     */
    public function getHasRide()
    {
        return $this->container['has_ride'];
    }

    /**
     * Sets has_ride
     *
     * @param bool $has_ride has_ride
     *
     * @return $this
     */
    public function setHasRide($has_ride)
    {
        $this->container['has_ride'] = $has_ride;

        return $this;
    }

    /**
     * Gets sms_code
     *
     * @return int
     */
    public function getSmsCode()
    {
        return $this->container['sms_code'];
    }

    /**
     * Sets sms_code
     *
     * @param int $sms_code sms_code
     *
     * @return $this
     */
    public function setSmsCode($sms_code)
    {
        $this->container['sms_code'] = $sms_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


