<?php
/**
 * ReportTripsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * traccar
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReportTripsTest Class Doc Comment
 *
 * @category    Class */
// * @description ReportTrips
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReportTripsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReportTrips"
     */
    public function testReportTrips()
    {
    }

    /**
     * Test attribute "device_id"
     */
    public function testPropertyDeviceId()
    {
    }

    /**
     * Test attribute "device_name"
     */
    public function testPropertyDeviceName()
    {
    }

    /**
     * Test attribute "max_speed"
     */
    public function testPropertyMaxSpeed()
    {
    }

    /**
     * Test attribute "average_speed"
     */
    public function testPropertyAverageSpeed()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "spent_fuel"
     */
    public function testPropertySpentFuel()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "start_address"
     */
    public function testPropertyStartAddress()
    {
    }

    /**
     * Test attribute "start_lat"
     */
    public function testPropertyStartLat()
    {
    }

    /**
     * Test attribute "start_lon"
     */
    public function testPropertyStartLon()
    {
    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
    }

    /**
     * Test attribute "end_address"
     */
    public function testPropertyEndAddress()
    {
    }

    /**
     * Test attribute "end_lat"
     */
    public function testPropertyEndLat()
    {
    }

    /**
     * Test attribute "end_lon"
     */
    public function testPropertyEndLon()
    {
    }

    /**
     * Test attribute "driver_unique_id"
     */
    public function testPropertyDriverUniqueId()
    {
    }

    /**
     * Test attribute "driver_name"
     */
    public function testPropertyDriverName()
    {
    }
}
