<?php
/**
 * ServerAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * traccar
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ServerAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description ServerAttributes
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServerAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ServerAttributes"
     */
    public function testServerAttributes()
    {
    }

    /**
     * Test attribute "stripepk"
     */
    public function testPropertyStripepk()
    {
    }

    /**
     * Test attribute "stripepklive"
     */
    public function testPropertyStripepklive()
    {
    }

    /**
     * Test attribute "stripeurllocalhost"
     */
    public function testPropertyStripeurllocalhost()
    {
    }

    /**
     * Test attribute "tracurl"
     */
    public function testPropertyTracurl()
    {
    }

    /**
     * Test attribute "tractoken"
     */
    public function testPropertyTractoken()
    {
    }

    /**
     * Test attribute "tracapi"
     */
    public function testPropertyTracapi()
    {
    }

    /**
     * Test attribute "stripeurl"
     */
    public function testPropertyStripeurl()
    {
    }

    /**
     * Test attribute "apple_merchant_id"
     */
    public function testPropertyAppleMerchantId()
    {
    }

    /**
     * Test attribute "b_enable_mockup_gps"
     */
    public function testPropertyBEnableMockupGps()
    {
    }
}
