<?php
/**
 * ServerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * traccar
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ServerTest Class Doc Comment
 *
 * @category    Class */
// * @description Server
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Server"
     */
    public function testServer()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "registration"
     */
    public function testPropertyRegistration()
    {
    }

    /**
     * Test attribute "readonly"
     */
    public function testPropertyReadonly()
    {
    }

    /**
     * Test attribute "device_readonly"
     */
    public function testPropertyDeviceReadonly()
    {
    }

    /**
     * Test attribute "limit_commands"
     */
    public function testPropertyLimitCommands()
    {
    }

    /**
     * Test attribute "map"
     */
    public function testPropertyMap()
    {
    }

    /**
     * Test attribute "bing_key"
     */
    public function testPropertyBingKey()
    {
    }

    /**
     * Test attribute "map_url"
     */
    public function testPropertyMapUrl()
    {
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
    }

    /**
     * Test attribute "zoom"
     */
    public function testPropertyZoom()
    {
    }

    /**
     * Test attribute "twelve_hour_format"
     */
    public function testPropertyTwelveHourFormat()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "force_settings"
     */
    public function testPropertyForceSettings()
    {
    }

    /**
     * Test attribute "coordinate_format"
     */
    public function testPropertyCoordinateFormat()
    {
    }
}
