<?php
/**
 * StatisticsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * traccar
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StatisticsTest Class Doc Comment
 *
 * @category    Class */
// * @description Statistics
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StatisticsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Statistics"
     */
    public function testStatistics()
    {
    }

    /**
     * Test attribute "capture_time"
     */
    public function testPropertyCaptureTime()
    {
    }

    /**
     * Test attribute "active_users"
     */
    public function testPropertyActiveUsers()
    {
    }

    /**
     * Test attribute "active_devices"
     */
    public function testPropertyActiveDevices()
    {
    }

    /**
     * Test attribute "requests"
     */
    public function testPropertyRequests()
    {
    }

    /**
     * Test attribute "messages_received"
     */
    public function testPropertyMessagesReceived()
    {
    }

    /**
     * Test attribute "messages_stored"
     */
    public function testPropertyMessagesStored()
    {
    }
}
