<?php
/**
 * UserAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * traccar
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserAttributesTest Class Doc Comment
 *
 * @category    Class */
// * @description UserAttributes
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserAttributes"
     */
    public function testUserAttributes()
    {
    }

    /**
     * Test attribute "has_email"
     */
    public function testPropertyHasEmail()
    {
    }

    /**
     * Test attribute "has_phone"
     */
    public function testPropertyHasPhone()
    {
    }

    /**
     * Test attribute "has_phone_verified"
     */
    public function testPropertyHasPhoneVerified()
    {
    }

    /**
     * Test attribute "has_deposit"
     */
    public function testPropertyHasDeposit()
    {
    }

    /**
     * Test attribute "has_ride"
     */
    public function testPropertyHasRide()
    {
    }
}
